title = "The Sesame Engineering Blog"
baseURL = "https://sesameengineering.github.io"
languageCode = "en-us"
theme = "ananke"
meta = "The intersectionality of loving the planet, openness and engineering"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 8 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "daily"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "Sesame Engineering Blog Space"
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = "https://github.com/SesameEngineering/Projects"
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  copyright = "ITRenew Inc"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/sesame-eng-hero.jpg"
  recent_posts_number = 4
  omit_header_text = true
  body_classes = "sans-serif"
  custom_css = ["dist/css/style.css"]
